spring:
  application:
    name: spring-cloud-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/carlosfls/microservices-with-spring-cloud.git

server:
  port: 8888